"""
The plain-English cache for agenda items: data/meta/agenda_summaries.json.

Two modules share it and neither should own it — ingest.summarize_agenda writes
it from the `claude` CLI, and ingest.build_upcoming merges it back into
docs/data.upcoming.json on every rebuild — so the key function and the file
format live here on their own.

Entries are keyed by a hash of the item's own words, not by its agenda number.
Agenda numbering restarts at 1 every meeting and shifts whenever an item is
added, so a number-keyed cache would hand August's sentence to September's item.
Hashing the text also means an amended agenda re-summarizes exactly the items
whose wording changed.
"""

from __future__ import annotations

import hashlib
import json

from . import bodies

CACHE = bodies.META / "agenda_summaries.json"


def item_key(item: dict) -> str:
    """Stable content hash for one agenda item."""
    basis = "|".join(
        str(item.get(f) or "") for f in ("kind", "title", "background")
    )
    return hashlib.sha1(basis.encode("utf-8")).hexdigest()[:16]


def load_cache() -> dict[str, dict]:
    if not CACHE.exists():
        return {}
    try:
        return json.loads(CACHE.read_text()).get("summaries") or {}
    except (json.JSONDecodeError, OSError):
        return {}


def save_cache(summaries: dict[str, dict]) -> None:
    CACHE.parent.mkdir(parents=True, exist_ok=True)
    doc = {
        "comment": (
            "One plain-English sentence per agenda item, generated by "
            "`python -m ingest.summarize_agenda` and merged into "
            "docs/data.upcoming.json by build_upcoming. Keyed by a content hash "
            "of the item (see agenda_summaries.item_key) — NOT by agenda number, "
            "which restarts every meeting. Safe to hand-edit: a corrected "
            "sentence is never overwritten unless you pass --force."
        ),
        "summaries": dict(sorted(summaries.items())),
    }
    CACHE.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n")
