"""
Generate plain-English headlines + summaries for motions and cache them in
data/meta/motion_summaries*.json, which build_dataset merges into docs/data*.json.

  python -m ingest.summarize_motions --limit 12          # newest 12 meetings, default body
  python -m ingest.summarize_motions --all               # backfill every meeting (slow, costs credits)
  python -m ingest.summarize_motions --only 726          # one meeting by event id
  python -m ingest.summarize_motions --force --limit 4   # re-summarize even if cached

Why this exists: the parsed record only carries legalese ("An Ordinance of Eagle
Mountain City, Utah, amending Municipal Code 16.15 Concept Plans adding condition
that council be notified…"). The site's job is to say what the council actually
decided, so each motion gets:

  headline — a short plain-language title      ("Widen Pony Express Parkway")
  summary  — one sentence on what was decided  ("The city approved $2.4M to add
                                                lanes on the main route out of town.")
  impact   — what it means for residents       ("Expect construction delays on Pony
                                                Express through 2027; after that the
                                                morning backup at Ranches Parkway
                                                should ease.")

The `impact` field is the one residents actually came for, and it is also the easiest
to fake. It must stay honest: plenty of motions are pure housekeeping, and for those
the right answer is to say so plainly rather than to invent a consequence.

Design notes, following the conventions already in this repo:

* Like scripts/transcribe_meeting.sh, this shells out to the `claude` CLI in
  headless mode rather than pulling in an LLM SDK. No API key to manage — it
  rides your existing CLI auth. If `claude` isn't installed we warn and exit 0
  so the build never hard-fails on a missing optional tool.

* Like crawl.py and the transcribe script, it is idempotent: a motion already in
  the cache is skipped unless --force. The weekly CI ingest never calls this, so
  CI stays LLM-free; run it locally and commit the meta file.

* Entries are keyed by a hash of the motion's *content*, not its `id`. Motion ids
  are a running counter assigned in filename order, so back-filling an older PDF
  renumbers every motion after it — an id-keyed cache would silently reattach
  summaries to the wrong motions.

* One `claude` call per meeting, not per motion. That is ~200 calls instead of
  ~1,100 for a full backfill, and it lets the model see the neighboring items,
  which is what makes "the typical homeowner pays about $18 more" possible.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
from . import bodies  # noqa: E402

# A meeting with many motions still fits comfortably in one call; this is a guard
# against a pathological parse producing a giant prompt.
MAX_MOTIONS_PER_CALL = 25
CLAUDE_TIMEOUT_S = 300


def cache_path(body: dict) -> Path:
    """data/meta/motion_summaries.json for City Council, .<body>.json for the rest."""
    name = body.get("motion_summaries")
    if not name:
        name = (
            "motion_summaries.json"
            if body.get("default")
            else f"motion_summaries.{body['id']}.json"
        )
    return bodies.META / name


def motion_key(motion: dict) -> str:
    """Stable content hash. Survives motion-id renumbering; changes if the parser
    starts reading the underlying text differently (which is when we *want* a
    re-summarize)."""
    basis = "|".join(
        str(motion.get(f) or "")
        for f in ("meeting_id", "agenda_ref", "item_title", "motion")
    )
    return hashlib.sha1(basis.encode("utf-8")).hexdigest()[:16]


def load_cache(path: Path) -> dict[str, dict]:
    if not path.exists():
        return {}
    raw = json.loads(path.read_text())
    return raw.get("summaries") or {}


def save_cache(path: Path, summaries: dict[str, dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    doc = {
        "comment": (
            "Plain-English headlines + summaries per motion, generated by "
            "`python -m ingest.summarize_motions` and merged into docs/data*.json "
            "by build_dataset. Keyed by a content hash of the motion (see "
            "summarize_motions.motion_key) — NOT by motion id, which renumbers. "
            "Safe to hand-edit: a corrected entry is never overwritten unless you "
            "pass --force."
        ),
        "summaries": dict(sorted(summaries.items())),
    }
    path.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n")


PROMPT = """\
You are writing plain-English descriptions of decisions made by the Eagle Mountain,
Utah City Council, for a public transparency site read by residents and local
journalists. Assume the reader has no legal or municipal background.

For EACH numbered motion below, produce:

  "headline" — a short, concrete title in plain language, sentence case, no final
               period, at most 60 characters. Name the actual thing being decided.
               Good: "Widen Pony Express Parkway"
                     "Rezone 40 acres near The Ranches"
                     "Property tax rate raised 0.9%"
               Bad:  "Ordinance 2026-14"  (means nothing to a resident)
                     "An Ordinance of Eagle Mountain City, Utah, amending…"  (legalese)

  "summary"  — ONE sentence, at most 30 words, saying what the council actually did.
               Lead with the decision, not the procedure. Include the concrete figure
               (dollars, acres, percent, units) when the motion states one.
               Good: "The city approved $2.4M to add lanes on Pony Express Parkway,
                      the main route out of the valley."
               Bad:  "The council voted to adopt the ordinance as presented."

  "impact"   — ONE or TWO sentences, at most 45 words, on what this means for an
               ordinary resident: what changes, who it touches, what they will see,
               pay, or have to do, and when. Address the reader as "you" where it fits,
               and be concrete about WHO is affected — the whole city, one
               neighborhood, homeowners, developers, a single business.
               Good: "Expect lane closures on Pony Express through 2027. Once it opens,
                      the morning backup at Ranches Parkway should ease."
               Good: "Nothing changes day to day — this is the routine paperwork the
                      city files to keep the grant money flowing."
               Bad:  "This decision may have various impacts on the community."  (says nothing)
               Bad:  "Residents will benefit from improved services."  (invented)

  "significance" — exactly one of "notable" or "routine". This is a routing decision,
               not a compliment: the site uses it to push housekeeping into the
               background so the decisions that actually reach a resident stand out.

               "notable" — a resident's money, property, neighborhood, services, or
                 rights are touched. Taxes and fees; utility rates; a budget that
                 commits real dollars to a real thing; rezoning, annexation, or a
                 development agreement; road and park projects; an ordinance that
                 changes what you may do on your own property; large contracts;
                 anything affecting police, fire, water, or sewer service.

               "routine" — the machinery of governing. Approving minutes or an
                 agenda; setting a public hearing date; reappointing someone to a
                 board; ceremonial items and proclamations; tabling or continuing an
                 item; renewing a routine contract; interfund bookkeeping that moves
                 money between accounts without changing what the city does.

               When genuinely torn, choose "routine". The cost of wrongly demoting one
               decision is that a resident has to scroll; the cost of marking
               everything "notable" is that the flag stops meaning anything at all.

HONESTY ABOUT IMPACT — the most important rule on this page.
Most motions are procedural: approving minutes, setting a public hearing date, renewing
a routine contract, appointing someone to a board. A resident feels nothing. When that
is the case, SAY SO plainly ("This is routine housekeeping — nothing changes for
residents") instead of manufacturing a consequence. A truthful "this one doesn't affect
you" is more useful than an invented effect, and inventing effects would destroy the
credibility of the whole site. Never inflate a small item into a big one.

RULES
- Ground every word ONLY in the motion text below. Do NOT invent figures, names,
  addresses, dollar amounts, or effects that are not stated. If the motion is too
  thin to say anything concrete, write a summary that plainly says what little was
  decided — never pad it with invented specifics. This applies double to "impact":
  if the motion does not support a claim about what residents will see or pay, do
  not make one.
- Describe the DECISION, not the parliamentary mechanics. Do not write "Councilmember
  X moved to…" or "seconded" or "the motion carried".
- Do not state the vote count or the outcome — the page already shows those next to
  your text, and repeating them wastes the sentence.
- Write in past tense for decided items ("The city approved…", "The council rejected…").
  If the outcome is unclear or the item was continued/tabled, describe it neutrally
  ("The council delayed a decision on…").
- Use plain words: "zoning change" not "rezone application"; "apartments" not
  "multi-family residential units"; "sewer plant" not "wastewater treatment facility".

Output ONLY a JSON object mapping each motion's number (as a string) to an object with
"headline", "summary", "impact", and "significance". No markdown, no code fence, no
commentary.

Example of the exact output shape:
{"1": {"headline": "Widen Pony Express Parkway", "summary": "The city approved $2.4M to add lanes on Pony Express Parkway, the main route out of the valley.", "impact": "Expect lane closures through 2027. Once it opens, the morning backup at Ranches Parkway should ease.", "significance": "notable"}, "2": {"headline": "March minutes approved", "summary": "The council approved the minutes of its March 4 meeting.", "impact": "Nothing changes for residents — this is the record-keeping step that makes the last meeting official.", "significance": "routine"}}
"""


def build_prompt(meeting_date: str, motions: list[dict]) -> str:
    lines = [PROMPT, f"\n=== MEETING: {meeting_date} ===\n"]
    for i, m in enumerate(motions, 1):
        lines.append(f"--- MOTION {i} ---")
        if m.get("business_type"):
            lines.append(f"Type: {m['business_type']}")
        if m.get("agenda_ref"):
            lines.append(f"Agenda item: {m['agenda_ref']}")
        if m.get("item_title"):
            lines.append(f"Title: {m['item_title']}")
        if m.get("motion"):
            lines.append(f"Motion as recorded: {m['motion']}")
        if m.get("outcome"):
            lines.append(f"Outcome (context only — do not restate): {m['outcome']}")
        lines.append("")
    return "\n".join(lines)


def call_claude(prompt: str) -> dict:
    """Run `claude -p` and parse its JSON reply. Raises on failure."""
    proc = subprocess.run(
        ["claude", "-p"],
        input=prompt,
        capture_output=True,
        text=True,
        timeout=CLAUDE_TIMEOUT_S,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"claude exited {proc.returncode}: {proc.stderr.strip()[:300]}")

    out = proc.stdout.strip()
    if not out:
        raise RuntimeError("claude returned nothing")
    # Tolerate a stray ```json fence even though the prompt forbids one.
    if out.startswith("```"):
        out = out.split("\n", 1)[1] if "\n" in out else out
        out = out.rsplit("```", 1)[0]
    start, end = out.find("{"), out.rfind("}")
    if start == -1 or end == -1:
        raise RuntimeError(f"no JSON object in claude output: {out[:200]!r}")
    return json.loads(out[start : end + 1])


def clean(text: str, limit: int) -> str:
    text = " ".join(str(text or "").split())
    return text[:limit].rstrip(" ,;:")


SIGNIFICANCE = ("notable", "routine")


def clean_significance(value: str) -> str:
    """Anything the model didn't say exactly becomes "routine". The flag only earns
    its keep if "notable" is a claim something had to satisfy — a typo or an
    invented third tier defaulting to "notable" would quietly inflate the site."""
    v = str(value or "").strip().lower()
    return v if v in SIGNIFICANCE else "routine"


def summarize_meeting(meeting_date: str, motions: list[dict]) -> dict[str, dict]:
    """-> {motion_key: {headline, summary, impact, significance}} for one meeting."""
    reply = call_claude(build_prompt(meeting_date, motions))
    out: dict[str, dict] = {}
    for i, m in enumerate(motions, 1):
        got = reply.get(str(i)) or {}
        headline = clean(got.get("headline"), 80)
        summary = clean(got.get("summary"), 320)
        impact = clean(got.get("impact"), 400)
        if not headline and not summary:
            continue
        out[motion_key(m)] = {
            "headline": headline,
            "summary": summary,
            "impact": impact,
            "significance": clean_significance(got.get("significance")),
        }
    return out


def is_stale(entry: dict) -> bool:
    """True if a cached entry predates a field the site now renders, so a plain
    re-run tops it up. Without this, motions summarized before `impact` and
    `significance` existed would keep their old entry until someone passed --force —
    and --force would also overwrite hand-corrected text, which we don't want."""
    return not entry.get("impact") or entry.get("significance") not in SIGNIFICANCE


def run_body(body: dict, args: argparse.Namespace) -> int:
    data_file = bodies.data_file(body)
    if not data_file.exists():
        print(f"  {body['id']}: no {data_file.name} yet — run build_dataset first", file=sys.stderr)
        return 0

    data = json.loads(data_file.read_text())
    path = cache_path(body)
    cache = load_cache(path)

    by_meeting: dict[int, list[dict]] = {}
    for m in data.get("motions", []):
        by_meeting.setdefault(m["meeting_id"], []).append(m)

    # Newest meetings first — the homepage and the motions list both lead with
    # recent decisions, so a partial run is still a useful run.
    meetings = sorted(data.get("meetings", []), key=lambda m: m["date"], reverse=True)
    if args.only:
        meetings = [m for m in meetings if m["id"] == args.only]
        if not meetings:
            print(f"  {body['id']}: no meeting with id {args.only}", file=sys.stderr)
            return 1
    if args.since:
        meetings = [m for m in meetings if m["date"] >= args.since]
    if args.limit and not args.all:
        meetings = meetings[: args.limit]

    print(f"\n== {body['label']} ({body['id']}) ==")
    print(f"  cache: {path.relative_to(ROOT)} ({len(cache)} motions already summarized)")

    todo: list[tuple[dict, list[dict]]] = []
    skipped = 0
    for meeting in meetings:
        motions = by_meeting.get(meeting["id"], [])
        if not motions:
            continue
        pending = (
            motions
            if args.force
            else [
                m
                for m in motions
                if motion_key(m) not in cache or is_stale(cache[motion_key(m)])
            ]
        )
        skipped += len(motions) - len(pending)
        if pending:
            todo.append((meeting, pending))

    pending_count = sum(len(p) for _, p in todo)
    print(f"  {pending_count} motions to summarize across {len(todo)} meetings ({skipped} cached)")
    if args.dry_run:
        for meeting, pending in todo:
            print(f"    would summarize {meeting['date']} (#{meeting['id']}): {len(pending)} motions")
        return 0
    if not todo:
        print("  nothing to do")
        return 0

    failures = 0
    for n, (meeting, pending) in enumerate(todo, 1):
        label = f"{meeting['date']} (#{meeting['id']})"
        for chunk_start in range(0, len(pending), MAX_MOTIONS_PER_CALL):
            chunk = pending[chunk_start : chunk_start + MAX_MOTIONS_PER_CALL]
            try:
                got = summarize_meeting(meeting["date"], chunk)
            except Exception as exc:
                print(f"  ! [{n}/{len(todo)}] {label}: {exc}", file=sys.stderr)
                failures += 1
                continue
            cache.update(got)
            print(f"  ✓ [{n}/{len(todo)}] {label}: {len(got)}/{len(chunk)} motions")
            # Checkpoint after every call — an LLM backfill is slow and expensive,
            # and a Ctrl-C at meeting 140 should not throw away the first 139.
            save_cache(path, cache)

    print(f"  wrote {path.relative_to(ROOT)} ({len(cache)} motions)")
    if failures:
        print(f"  {failures} meeting(s) failed — re-run to retry just those", file=sys.stderr)
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--body", help="body id (default: the default body)")
    ap.add_argument("--all-bodies", action="store_true", help="every registered body")
    ap.add_argument("--limit", type=int, default=12, help="newest N meetings (default 12)")
    ap.add_argument("--all", action="store_true", help="every meeting — slow, costs credits")
    ap.add_argument("--only", type=int, help="a single meeting by event id")
    ap.add_argument("--since", help="only meetings on/after this YYYY-MM-DD")
    ap.add_argument("--force", action="store_true", help="re-summarize motions already cached")
    ap.add_argument("--dry-run", action="store_true", help="show what would run; no LLM calls")
    args = ap.parse_args()

    if not args.dry_run and not shutil.which("claude"):
        print(
            "⚠ `claude` CLI not found — skipping motion summaries. The site still "
            "builds; cards fall back to the cleaned motion title.",
            file=sys.stderr,
        )
        return 0

    targets = (
        bodies.all_bodies()
        if args.all_bodies
        else [bodies.get_body(args.body) if args.body else bodies.default_body()]
    )
    rc = 0
    for body in targets:
        rc |= run_body(body, args)
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
